version: 2
updates:
  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/" # location of package.json
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "deps(js)"
    rebase-strategy: "auto"
